'':
  - ttl: 1800
    type: TXT
    value: v=spf1 include:_spf.google.com ~all
  - ttl: 1800
    type: NS
    values:
      - ns1.digitalocean.com.
      - ns2.digitalocean.com.
      - ns3.digitalocean.com.
  - ttl: 1800
    type: MX
    values:
      - exchange: aspmx.l.google.com.
        preference: 1
      - exchange: alt1.aspmx.l.google.com.
        preference: 5
      - exchange: alt2.aspmx.l.google.com.
        preference: 5
      - exchange: alt3.aspmx.l.google.com.
        preference: 10
      - exchange: alt4.aspmx.l.google.com.
        preference: 10

b:
  type: CNAME
  value: frosty-heyrovsky-dc5b99.netlify.com.

blog:
  type: CNAME
  value: epic-jepsen-634955.netlify.com.

www:
  type: CNAME
  value: epic-jepsen-634955.netlify.com.
