manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    enforce_order: True
    default_ttl: 360
  digitalocean:
    class: octodns.provider.digitalocean.DigitalOceanProvider
    token: env/DIGITALOCEAN_TOKEN

zones:
  horn.uk.:
    sources:
      - config
    targets:
      - digitalocean
